<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <TargetFramework>net11.0</TargetFramework>
        <RootNamespace>UUIDSerializationEntityTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\UUID\UUID.csproj" />
        <ProjectReference Include="..\..\src\UUID.Serialization.Entity\UUID.Serialization.Entity.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.0.0-rc.2.26455.110" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.0.0-rc.2.26455.110" />
    </ItemGroup>

</Project>