title: UUID Documentation
description: Modern and efficient unique identifier generator for .NET ecosystem
theme: jekyll-theme-cayman

baseurl: "/UUID"
url: "https://taiizor.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

github:
  is_project_page: true
  repository_url: https://github.com/Taiizor/UUID
  repository_name: UUID
  owner_url: https://github.com/Taiizor
  owner_name: Taiizor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - index.html
  - README.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor