<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <DebugType>pdbonly</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <TargetFramework>net11.0</TargetFramework>
        <RootNamespace>UUIDSerializationNewtonsoftBenchmarks</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\UUID\UUID.csproj" />
        <ProjectReference Include="..\..\src\UUID.Serialization.Newtonsoft\UUID.Serialization.Newtonsoft.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
        <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.2" />
    </ItemGroup>

</Project>