name: .NET Desktop

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  Build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [
            Release
        ]
        solution: [
            UUID.slnx,
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 11.0.x
        dotnet-quality: preview

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    # Execute all unit tests in the solution
    - name: Execute Unit Tests
      run: dotnet test ${{ matrix.solution }} -c ${{ matrix.configuration }} -p:NoWarn="CS0067%3BCS0108%3BCS0109%3BCS0114%3BCS0169%3BCS0414%3BCS0649%3BCA1416%3BNU5104%3BNETSDK1138%3BSYSLIB0003"
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the UUID
      run: msbuild ${{ matrix.solution }} /t:Restore /p:Configuration=$env:Configuration
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config
        Configuration: ${{ matrix.configuration }}